"""Generate guide/reference/*.md from the code, so documentation cannot drift.

    uv run python -m scripts.gen_docs

THE ONE RULE. Every generator here reads CLASS-LEVEL metadata and module
constants -- Settings.model_fields, OPERATIONAL_KEYS, pricing._RATES,
deploy.CHECKS -- and NEVER config.settings. model_fields carries each
field's DECLARED DEFAULT; the settings instance carries this machine's real
DATABASE_URL, API keys, and service-account material. Everything written here
is committed and published, so reading the instance would publish those
values. Import the Settings CLASS only; the module-level instance in
config.py must never be imported here. tests/test_gen_docs.py pins this
both behaviourally and by parsing this module's own import statements.

Output must be DETERMINISTIC -- no timestamps, no unordered iteration, no
absolute paths. The CI drift job compares byte-for-byte, so any run-to-run
variation is a permanently red build rather than a useful signal.

The lists and tables each renderer builds are generated FROM the code above
and so cannot drift from it. The hand-written PROSE surrounding them (the
explanatory paragraphs in e.g. render_checks()/render_sync_env()) is not: no
test enforces that it still accurately describes actual behaviour, so an
editor changing what a renderer's code does must also re-read and, if needed,
update its surrounding prose by hand -- not just the generated table/list.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from pydantic_core import PydanticUndefined

from config import OPERATIONAL_KEYS, Settings
from providers import pricing, registry
from scripts import deploy

GENERATED_HEADER = (
    "<!-- generated by scripts.gen_docs -- do not edit by hand.\n"
    "     Change the code it reads, then run: uv run python -m scripts.gen_docs -->\n"
)


def _type_name(annotation: object) -> str:
    """A readable type for the table. str(annotation) renders unions as
    'float | None' already; the getattr picks the friendlier name for plain
    classes ('int', not "<class 'int'>")."""
    return getattr(annotation, "__name__", None) or str(annotation)


def _default_text(field) -> str:
    """The DECLARED default -- class-level, never a configured value.

    No Settings field lacks a default today (a default_factory-only field
    would also have field.default be the sentinel below), so this branch is
    defensive: it guards against a future field added with no plain default
    at all. Without it, field.default would be pydantic's own PydanticUndefined
    sentinel object, and the final `f"`{default}`"` fallback would render the
    literal string "PydanticUndefined" into a published doc.
    """
    default = field.default
    if default is PydanticUndefined:
        return "*(required — no default)*"
    if default is None:
        return "`None`"
    if default == "":
        return "*(empty)*"
    return f"`{default}`"


def render_config() -> str:
    """Every Settings field, and which of the two config files it belongs in.

    Secret-by-default, exactly as config.py's OPERATIONAL_KEYS defines it:
    a name on that list is operational and lives in .env.config; everything
    else is a credential and lives in .env.
    """
    lines = [
        GENERATED_HEADER,
        "# Configuration reference\n",
        "Every setting this service reads. `.env.config` holds operational "
        "settings and is safe to open and edit; `.env` holds credentials and "
        "identity.\n",
        "| Setting | Type | Default | Lives in |",
        "| --- | --- | --- | --- |",
    ]
    for name, field in Settings.model_fields.items():
        env_name = name.upper()
        home = ".env.config" if env_name in OPERATIONAL_KEYS else ".env"
        lines.append(
            f"| `{env_name}` | `{_type_name(field.annotation)}` | "
            f"{_default_text(field)} | `{home}` |"
        )
    return "\n".join(lines) + "\n"


def _escape_cell(text: str) -> str:
    """A literal `|` would corrupt a Markdown table's column structure."""
    return text.replace("|", "\\|")


def render_pricing() -> str:
    """The rate table, with each entry's provenance.

    Sorted explicitly: dict order is stable in practice, but the drift check
    compares byte-for-byte and a reordered _RATES literal should not read as a
    documentation change.
    """
    lines = [
        GENERATED_HEADER,
        "# Model pricing\n",
        "Rates are USD per 1M tokens. Pricing is **optional**: a model with no "
        "entry here still runs, the PR comment simply appears without a cost "
        "estimate, and `scripts/deploy.py` reports it as a warning rather than "
        "blocking the deploy.\n",
        "| Provider | Model | In | Out | Verified | Source |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    caveats: list[str] = []
    for (provider, model), rate in sorted(pricing._RATES.items()):
        marker = " †" if rate.note else ""
        lines.append(
            f"| `{provider}` | `{model}` | {rate.rate_in:.2f} | {rate.rate_out:.2f} | "
            f"{rate.verified}{marker} | [source]({rate.source_url}) |"
        )
        if rate.note:
            caveats.append(f"† `{provider}`/`{model}`: {rate.note}")
    if caveats:
        lines.append("")
        lines.extend(caveats)
    return "\n".join(lines) + "\n"


def render_sync_env() -> str:
    """What `--sync-env` pushes to Render, and what it deliberately never does.

    The second half matters more than the first: a setting that looks like an
    env var but lives only in the database is exactly the thing an operator
    edits, redeploys, and then cannot explain the non-effect of.
    """
    always = sorted(deploy._ALWAYS_SYNCED)
    credentials = sorted({c for c, _m in registry.PROVIDERS.values()})
    model_seeds = sorted({m for _c, m in registry.PROVIDERS.values()})
    generic = sorted(deploy._GENERIC_OPERATIONAL_ENV_ATTRS)
    db_only = sorted(deploy._DB_SYNCED_OPERATIONAL_KEYS)
    never = sorted(deploy._NEVER_SYNCED_OPERATIONAL_KEYS)

    def bullets(names: list[str]) -> list[str]:
        return [f"- `{name}`" for name in names]

    return "\n".join(
        [
            GENERATED_HEADER,
            "# What `--sync-env` pushes\n",
            "## Always pushed\n",
            *bullets(always),
            "",
            "Plus `LLM_PROVIDER`, and `GITHUB_APP_INSTALLATION_ID` once it is set "
            "locally (it is optional, so an empty value is not an error).\n",
            "## Never pushed: per-slot model, project, and location\n",
            *bullets(model_seeds),
            "",
            "These are **not** Render env vars. Since the 2026-09-08 slotted-config "
            "change, the model in force -- and, for Vertex, the GCP project and "
            "location -- live per credential slot in the `slot_config` database "
            "table, so different key slots can run different models and regions "
            "with no redeploy. The values above are read from `.env.config` exactly "
            "once, as the seed for the active provider's slot 0, the first time "
            "`--sync-env` runs against a database with no row for it. After that, "
            "change them in the dashboard's Environment tab (or `uv run python -m "
            "scripts.set_override <provider> --index N --model M`) -- editing "
            "`.env.config` and redeploying does nothing.\n",
            "## Provider credentials\n",
            *bullets(credentials),
            "",
            "The selected provider's is always pushed. Another provider's is pushed "
            "only if you happen to have it set locally -- an unselected provider's "
            "key is never demanded.\n",
            "Each credential also has numbered key-rotation slots: additional vars "
            "named `{credential}_2`, `{credential}_3`, and so on -- the naming "
            "scheme is `registry.slot_env_name()`'s (`{base}` for slot 0, "
            "`{base}_{n}` for slot n>=1). Any slot that is configured locally is "
            "pushed too, for every provider, the same as the base credential above; "
            "this reference cannot say how many exist for you, since that would "
            "mean reading your local configured values, which this generator never "
            "does.\n",
            "## Operational settings\n",
            *bullets(generic),
            "",
            "## Never pushed: database-only settings\n",
            *bullets(db_only),
            "",
            "These live only in the `runtime_config` table, never as a Render env "
            "var, because the dispatcher must be able to change them with no "
            "redeploy. `uv run python -m scripts.deploy --sync-config-db` pushes "
            "them there. Editing one and redeploying does nothing on its own.\n",
            "## Never pushed: operator-machine settings\n",
            *bullets(never),
            "",
            "These configure your local tooling, not the service. Setting them on "
            "Render would create dead env vars.",
        ]
    ) + "\n"


def render_checks() -> str:
    """The deploy checklist, rendered from deploy.CHECKS in run order.

    Order is the registry's order, not sorted: the checks run foundational
    first so a misconfiguration is reported before the checks that would fail
    as a consequence of it, and the table is more useful read the same way.
    """
    lines = [
        GENERATED_HEADER,
        "# Deployment checks\n",
        "`uv run python -m scripts.deploy` runs all of these and prints one line "
        "each, so a single run surfaces every problem rather than only the "
        "first.\n",
        "| Check | Verifies | Always runs? |",
        "| --- | --- | --- |",
    ]
    for spec in deploy.CHECKS:
        lines.append(
            f"| `{spec.name}` | {_escape_cell(spec.verifies)} | "
            f"{'yes' if spec.required else 'needs an operator key'} |"
        )
    lines.extend(
        [
            "",
            "## Unskipping the optional checks\n",
            "An optional check degrades to `SKIPPED` with a hint, never to a "
            "failure, when its operator-local key is unset. `RENDER_API_KEY` "
            "and `UPTIMEROBOT_API_KEY` are both required now (see the guide's "
            "setup steps 6 and 8) -- only `DATABASE_URL` still leaves a check "
            "optional.\n",
            "- `DATABASE_URL` enables `database` and `provider` — the provider "
            "override lives in the same database.",
        ]
    )
    return "\n".join(lines) + "\n"


# The only directory this script may write to, and the only files it may
# create. Both are fixed, not configurable: a generator that can be pointed
# anywhere is one wrong argument away from replacing hand-written content.
REFERENCE_DIR = "guide/reference"

GENERATED_FILES = {
    "config.md": render_config,
    "pricing.md": render_pricing,
    "checks.md": render_checks,
    "sync-env.md": render_sync_env,
}


def write_all(root: Path) -> list[Path]:
    """Write every generated file under `root`/guide/reference; return them.

    A REPLACING writer by design -- these files have no hand-written content to
    preserve. What makes that safe is that it is confined to REFERENCE_DIR and
    to GENERATED_FILES' names, every output carries a do-not-edit header, CI
    fails on drift, and no hand-authored page is ever placed in this directory.

    The confinement is relative, not absolute: `root` itself (main()'s --root
    flag) is caller-supplied and can point anywhere, including outside this
    repository entirely -- only the `guide/reference` subpath under whatever
    root is given is fixed. That's deliberate (it's what lets the tmp_path-based
    tests below point this at a scratch directory) and does not need to be
    tightened; it just means "confined to REFERENCE_DIR" is a guarantee about
    the directory name, not a sandboxing guarantee about `root`.
    """
    target = root / REFERENCE_DIR
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, render in GENERATED_FILES.items():
        path = target / name
        path.write_text(render(), encoding="utf-8", newline="\n")
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate guide/reference/ from the code"
    )
    parser.add_argument("--root", default=".", help="repository root to write under")
    args = parser.parse_args(argv)
    for path in write_all(Path(args.root)):
        print(f"wrote {path.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
